services:
  frontend:
    build: ./ai-article-summerizer-front-end
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./ai-article-summerizer-back-end
    ports:
      - "5000:5000"
